services:
  next-ts-app:
    build: .
    container_name: next-ts-app
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - DJANGO_BACKEND_URL=${DJANGO_BACKEND_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
