/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAuthedRouteImport } from './routes/$locale/_authed'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LocaleAuthRegisterRouteImport } from './routes/$locale/auth/register'
import { Route as LocaleAuthLogoutRouteImport } from './routes/$locale/auth/logout'
import { Route as LocaleAuthLoginRouteImport } from './routes/$locale/auth/login'
import { Route as LocaleAuthForgotPasswordRouteImport } from './routes/$locale/auth/forgot-password'
import { Route as LocaleAuthedDeniedRouteImport } from './routes/$locale/_authed/denied'
import { Route as LocaleAuthedDashboardRouteImport } from './routes/$locale/_authed/dashboard'
import { Route as LocaleAuthedWishlistIndexRouteImport } from './routes/$locale/_authed/wishlist/index'
import { Route as LocaleAuthedOrdersIndexRouteImport } from './routes/$locale/_authed/orders/index'
import { Route as LocaleAuthedCartIndexRouteImport } from './routes/$locale/_authed/cart/index'
import { Route as LocaleAuthedUsersSearchRouteImport } from './routes/$locale/_authed/users/search'
import { Route as LocaleAuthedUsersCreateRouteImport } from './routes/$locale/_authed/users/create'
import { Route as LocaleAuthedProductsSearchRouteImport } from './routes/$locale/_authed/products/search'
import { Route as LocaleAuthedProductsCreateRouteImport } from './routes/$locale/_authed/products/create'
import { Route as LocaleAuthedUsersUuidIndexRouteImport } from './routes/$locale/_authed/users/$uuid/index'
import { Route as LocaleAuthedProductsUuidIndexRouteImport } from './routes/$locale/_authed/products/$uuid/index'
import { Route as LocaleAuthedOrdersUuidIndexRouteImport } from './routes/$locale/_authed/orders/$uuid/index'
import { Route as LocaleAuthedProductsUuidEditRouteImport } from './routes/$locale/_authed/products/$uuid/edit'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthedRoute = LocaleAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAuthRegisterRoute = LocaleAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthLogoutRoute = LocaleAuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthLoginRoute = LocaleAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthForgotPasswordRoute =
  LocaleAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAuthedDeniedRoute = LocaleAuthedDeniedRouteImport.update({
  id: '/denied',
  path: '/denied',
  getParentRoute: () => LocaleAuthedRoute,
} as any)
const LocaleAuthedDashboardRoute = LocaleAuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleAuthedRoute,
} as any)
const LocaleAuthedWishlistIndexRoute =
  LocaleAuthedWishlistIndexRouteImport.update({
    id: '/wishlist/',
    path: '/wishlist/',
    getParentRoute: () => LocaleAuthedRoute,
  } as any)
const LocaleAuthedOrdersIndexRoute = LocaleAuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LocaleAuthedRoute,
} as any)
const LocaleAuthedCartIndexRoute = LocaleAuthedCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => LocaleAuthedRoute,
} as any)
const LocaleAuthedUsersSearchRoute = LocaleAuthedUsersSearchRouteImport.update({
  id: '/users/search',
  path: '/users/search',
  getParentRoute: () => LocaleAuthedRoute,
} as any)
const LocaleAuthedUsersCreateRoute = LocaleAuthedUsersCreateRouteImport.update({
  id: '/users/create',
  path: '/users/create',
  getParentRoute: () => LocaleAuthedRoute,
} as any)
const LocaleAuthedProductsSearchRoute =
  LocaleAuthedProductsSearchRouteImport.update({
    id: '/products/search',
    path: '/products/search',
    getParentRoute: () => LocaleAuthedRoute,
  } as any)
const LocaleAuthedProductsCreateRoute =
  LocaleAuthedProductsCreateRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => LocaleAuthedRoute,
  } as any)
const LocaleAuthedUsersUuidIndexRoute =
  LocaleAuthedUsersUuidIndexRouteImport.update({
    id: '/users/$uuid/',
    path: '/users/$uuid/',
    getParentRoute: () => LocaleAuthedRoute,
  } as any)
const LocaleAuthedProductsUuidIndexRoute =
  LocaleAuthedProductsUuidIndexRouteImport.update({
    id: '/products/$uuid/',
    path: '/products/$uuid/',
    getParentRoute: () => LocaleAuthedRoute,
  } as any)
const LocaleAuthedOrdersUuidIndexRoute =
  LocaleAuthedOrdersUuidIndexRouteImport.update({
    id: '/orders/$uuid/',
    path: '/orders/$uuid/',
    getParentRoute: () => LocaleAuthedRoute,
  } as any)
const LocaleAuthedProductsUuidEditRoute =
  LocaleAuthedProductsUuidEditRouteImport.update({
    id: '/products/$uuid/edit',
    path: '/products/$uuid/edit',
    getParentRoute: () => LocaleAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/dashboard': typeof LocaleAuthedDashboardRoute
  '/$locale/denied': typeof LocaleAuthedDeniedRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/logout': typeof LocaleAuthLogoutRoute
  '/$locale/auth/register': typeof LocaleAuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/products/create': typeof LocaleAuthedProductsCreateRoute
  '/$locale/products/search': typeof LocaleAuthedProductsSearchRoute
  '/$locale/users/create': typeof LocaleAuthedUsersCreateRoute
  '/$locale/users/search': typeof LocaleAuthedUsersSearchRoute
  '/$locale/cart/': typeof LocaleAuthedCartIndexRoute
  '/$locale/orders/': typeof LocaleAuthedOrdersIndexRoute
  '/$locale/wishlist/': typeof LocaleAuthedWishlistIndexRoute
  '/$locale/products/$uuid/edit': typeof LocaleAuthedProductsUuidEditRoute
  '/$locale/orders/$uuid/': typeof LocaleAuthedOrdersUuidIndexRoute
  '/$locale/products/$uuid/': typeof LocaleAuthedProductsUuidIndexRoute
  '/$locale/users/$uuid/': typeof LocaleAuthedUsersUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/dashboard': typeof LocaleAuthedDashboardRoute
  '/$locale/denied': typeof LocaleAuthedDeniedRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/logout': typeof LocaleAuthLogoutRoute
  '/$locale/auth/register': typeof LocaleAuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/products/create': typeof LocaleAuthedProductsCreateRoute
  '/$locale/products/search': typeof LocaleAuthedProductsSearchRoute
  '/$locale/users/create': typeof LocaleAuthedUsersCreateRoute
  '/$locale/users/search': typeof LocaleAuthedUsersSearchRoute
  '/$locale/cart': typeof LocaleAuthedCartIndexRoute
  '/$locale/orders': typeof LocaleAuthedOrdersIndexRoute
  '/$locale/wishlist': typeof LocaleAuthedWishlistIndexRoute
  '/$locale/products/$uuid/edit': typeof LocaleAuthedProductsUuidEditRoute
  '/$locale/orders/$uuid': typeof LocaleAuthedOrdersUuidIndexRoute
  '/$locale/products/$uuid': typeof LocaleAuthedProductsUuidIndexRoute
  '/$locale/users/$uuid': typeof LocaleAuthedUsersUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_authed': typeof LocaleAuthedRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/_authed/dashboard': typeof LocaleAuthedDashboardRoute
  '/$locale/_authed/denied': typeof LocaleAuthedDeniedRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/logout': typeof LocaleAuthLogoutRoute
  '/$locale/auth/register': typeof LocaleAuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$locale/_authed/products/create': typeof LocaleAuthedProductsCreateRoute
  '/$locale/_authed/products/search': typeof LocaleAuthedProductsSearchRoute
  '/$locale/_authed/users/create': typeof LocaleAuthedUsersCreateRoute
  '/$locale/_authed/users/search': typeof LocaleAuthedUsersSearchRoute
  '/$locale/_authed/cart/': typeof LocaleAuthedCartIndexRoute
  '/$locale/_authed/orders/': typeof LocaleAuthedOrdersIndexRoute
  '/$locale/_authed/wishlist/': typeof LocaleAuthedWishlistIndexRoute
  '/$locale/_authed/products/$uuid/edit': typeof LocaleAuthedProductsUuidEditRoute
  '/$locale/_authed/orders/$uuid/': typeof LocaleAuthedOrdersUuidIndexRoute
  '/$locale/_authed/products/$uuid/': typeof LocaleAuthedProductsUuidIndexRoute
  '/$locale/_authed/users/$uuid/': typeof LocaleAuthedUsersUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/'
    | '/$locale/dashboard'
    | '/$locale/denied'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/login'
    | '/$locale/auth/logout'
    | '/$locale/auth/register'
    | '/api/auth/$'
    | '/$locale/products/create'
    | '/$locale/products/search'
    | '/$locale/users/create'
    | '/$locale/users/search'
    | '/$locale/cart/'
    | '/$locale/orders/'
    | '/$locale/wishlist/'
    | '/$locale/products/$uuid/edit'
    | '/$locale/orders/$uuid/'
    | '/$locale/products/$uuid/'
    | '/$locale/users/$uuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/dashboard'
    | '/$locale/denied'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/login'
    | '/$locale/auth/logout'
    | '/$locale/auth/register'
    | '/api/auth/$'
    | '/$locale/products/create'
    | '/$locale/products/search'
    | '/$locale/users/create'
    | '/$locale/users/search'
    | '/$locale/cart'
    | '/$locale/orders'
    | '/$locale/wishlist'
    | '/$locale/products/$uuid/edit'
    | '/$locale/orders/$uuid'
    | '/$locale/products/$uuid'
    | '/$locale/users/$uuid'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_authed'
    | '/$locale/'
    | '/$locale/_authed/dashboard'
    | '/$locale/_authed/denied'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/login'
    | '/$locale/auth/logout'
    | '/$locale/auth/register'
    | '/api/auth/$'
    | '/$locale/_authed/products/create'
    | '/$locale/_authed/products/search'
    | '/$locale/_authed/users/create'
    | '/$locale/_authed/users/search'
    | '/$locale/_authed/cart/'
    | '/$locale/_authed/orders/'
    | '/$locale/_authed/wishlist/'
    | '/$locale/_authed/products/$uuid/edit'
    | '/$locale/_authed/orders/$uuid/'
    | '/$locale/_authed/products/$uuid/'
    | '/$locale/_authed/users/$uuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authed': {
      id: '/$locale/_authed'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/auth/register': {
      id: '/$locale/auth/register'
      path: '/auth/register'
      fullPath: '/$locale/auth/register'
      preLoaderRoute: typeof LocaleAuthRegisterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/logout': {
      id: '/$locale/auth/logout'
      path: '/auth/logout'
      fullPath: '/$locale/auth/logout'
      preLoaderRoute: typeof LocaleAuthLogoutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/login': {
      id: '/$locale/auth/login'
      path: '/auth/login'
      fullPath: '/$locale/auth/login'
      preLoaderRoute: typeof LocaleAuthLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/forgot-password': {
      id: '/$locale/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/$locale/auth/forgot-password'
      preLoaderRoute: typeof LocaleAuthForgotPasswordRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authed/denied': {
      id: '/$locale/_authed/denied'
      path: '/denied'
      fullPath: '/$locale/denied'
      preLoaderRoute: typeof LocaleAuthedDeniedRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/dashboard': {
      id: '/$locale/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleAuthedDashboardRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/wishlist/': {
      id: '/$locale/_authed/wishlist/'
      path: '/wishlist'
      fullPath: '/$locale/wishlist/'
      preLoaderRoute: typeof LocaleAuthedWishlistIndexRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/orders/': {
      id: '/$locale/_authed/orders/'
      path: '/orders'
      fullPath: '/$locale/orders/'
      preLoaderRoute: typeof LocaleAuthedOrdersIndexRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/cart/': {
      id: '/$locale/_authed/cart/'
      path: '/cart'
      fullPath: '/$locale/cart/'
      preLoaderRoute: typeof LocaleAuthedCartIndexRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/users/search': {
      id: '/$locale/_authed/users/search'
      path: '/users/search'
      fullPath: '/$locale/users/search'
      preLoaderRoute: typeof LocaleAuthedUsersSearchRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/users/create': {
      id: '/$locale/_authed/users/create'
      path: '/users/create'
      fullPath: '/$locale/users/create'
      preLoaderRoute: typeof LocaleAuthedUsersCreateRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/products/search': {
      id: '/$locale/_authed/products/search'
      path: '/products/search'
      fullPath: '/$locale/products/search'
      preLoaderRoute: typeof LocaleAuthedProductsSearchRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/products/create': {
      id: '/$locale/_authed/products/create'
      path: '/products/create'
      fullPath: '/$locale/products/create'
      preLoaderRoute: typeof LocaleAuthedProductsCreateRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/users/$uuid/': {
      id: '/$locale/_authed/users/$uuid/'
      path: '/users/$uuid'
      fullPath: '/$locale/users/$uuid/'
      preLoaderRoute: typeof LocaleAuthedUsersUuidIndexRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/products/$uuid/': {
      id: '/$locale/_authed/products/$uuid/'
      path: '/products/$uuid'
      fullPath: '/$locale/products/$uuid/'
      preLoaderRoute: typeof LocaleAuthedProductsUuidIndexRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/orders/$uuid/': {
      id: '/$locale/_authed/orders/$uuid/'
      path: '/orders/$uuid'
      fullPath: '/$locale/orders/$uuid/'
      preLoaderRoute: typeof LocaleAuthedOrdersUuidIndexRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
    '/$locale/_authed/products/$uuid/edit': {
      id: '/$locale/_authed/products/$uuid/edit'
      path: '/products/$uuid/edit'
      fullPath: '/$locale/products/$uuid/edit'
      preLoaderRoute: typeof LocaleAuthedProductsUuidEditRouteImport
      parentRoute: typeof LocaleAuthedRoute
    }
  }
}

interface LocaleAuthedRouteChildren {
  LocaleAuthedDashboardRoute: typeof LocaleAuthedDashboardRoute
  LocaleAuthedDeniedRoute: typeof LocaleAuthedDeniedRoute
  LocaleAuthedProductsCreateRoute: typeof LocaleAuthedProductsCreateRoute
  LocaleAuthedProductsSearchRoute: typeof LocaleAuthedProductsSearchRoute
  LocaleAuthedUsersCreateRoute: typeof LocaleAuthedUsersCreateRoute
  LocaleAuthedUsersSearchRoute: typeof LocaleAuthedUsersSearchRoute
  LocaleAuthedCartIndexRoute: typeof LocaleAuthedCartIndexRoute
  LocaleAuthedOrdersIndexRoute: typeof LocaleAuthedOrdersIndexRoute
  LocaleAuthedWishlistIndexRoute: typeof LocaleAuthedWishlistIndexRoute
  LocaleAuthedProductsUuidEditRoute: typeof LocaleAuthedProductsUuidEditRoute
  LocaleAuthedOrdersUuidIndexRoute: typeof LocaleAuthedOrdersUuidIndexRoute
  LocaleAuthedProductsUuidIndexRoute: typeof LocaleAuthedProductsUuidIndexRoute
  LocaleAuthedUsersUuidIndexRoute: typeof LocaleAuthedUsersUuidIndexRoute
}

const LocaleAuthedRouteChildren: LocaleAuthedRouteChildren = {
  LocaleAuthedDashboardRoute: LocaleAuthedDashboardRoute,
  LocaleAuthedDeniedRoute: LocaleAuthedDeniedRoute,
  LocaleAuthedProductsCreateRoute: LocaleAuthedProductsCreateRoute,
  LocaleAuthedProductsSearchRoute: LocaleAuthedProductsSearchRoute,
  LocaleAuthedUsersCreateRoute: LocaleAuthedUsersCreateRoute,
  LocaleAuthedUsersSearchRoute: LocaleAuthedUsersSearchRoute,
  LocaleAuthedCartIndexRoute: LocaleAuthedCartIndexRoute,
  LocaleAuthedOrdersIndexRoute: LocaleAuthedOrdersIndexRoute,
  LocaleAuthedWishlistIndexRoute: LocaleAuthedWishlistIndexRoute,
  LocaleAuthedProductsUuidEditRoute: LocaleAuthedProductsUuidEditRoute,
  LocaleAuthedOrdersUuidIndexRoute: LocaleAuthedOrdersUuidIndexRoute,
  LocaleAuthedProductsUuidIndexRoute: LocaleAuthedProductsUuidIndexRoute,
  LocaleAuthedUsersUuidIndexRoute: LocaleAuthedUsersUuidIndexRoute,
}

const LocaleAuthedRouteWithChildren = LocaleAuthedRoute._addFileChildren(
  LocaleAuthedRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAuthedRoute: typeof LocaleAuthedRouteWithChildren
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleAuthForgotPasswordRoute: typeof LocaleAuthForgotPasswordRoute
  LocaleAuthLoginRoute: typeof LocaleAuthLoginRoute
  LocaleAuthLogoutRoute: typeof LocaleAuthLogoutRoute
  LocaleAuthRegisterRoute: typeof LocaleAuthRegisterRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAuthedRoute: LocaleAuthedRouteWithChildren,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleAuthForgotPasswordRoute: LocaleAuthForgotPasswordRoute,
  LocaleAuthLoginRoute: LocaleAuthLoginRoute,
  LocaleAuthLogoutRoute: LocaleAuthLogoutRoute,
  LocaleAuthRegisterRoute: LocaleAuthRegisterRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
